#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

[[ -f "$HOME/.aliases" ]] && rm -rf $HOME/.aliases
ln -s $DOTFILES/zsh/.aliases $HOME/.aliases

[[ -f "$HOME/.functions" ]] && rm -rf $HOME/.functions
ln -s $DOTFILES/zsh/.functions $HOME/.functions

[[ -f "$HOME/.zshrc" ]] && rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/.zshrc $HOME/.zshrc

[[ -d "$HOME/.config/nvim" ]] && rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

[[ -f "$HOME/.gitconfig" ]] && rm -rf $HOME/.gitconfig
ln -s $DOTFILES/git/.gitconfig $HOME/.gitconfig

[[ -f "$HOME/.czrc" ]] && rm -rf $HOME/.czrc
ln -s $DOTFILES/git/.czrc $HOME/.czrc

[[ -f "$HOME/.gitignore_global" ]] && rm -rf $HOME/.gitignore_global
ln -s $DOTFILES/git/.gitignore_global $HOME/.gitignore_global
